

const PRODUCTS = [
  {
    id: "1",
    name: "Men Casual Cotton Shirt",
    category: "men",
    tags: ["topwear", "trending"],
    price: 499,
    discount: 20,
    rating: 4.5,
    stock: 15,
    
    image: "https://assets.myntassets.com/dpr_1.5,q_30,w_400,c_limit,fl_progressive/assets/images/15557590/2022/2/18/a88d594a-0184-4042-baad-01c2d7874cec1645166286136-Roadster-Men-Shirts-4091645166285596-1.jpg",
  },
  {
    id: "2",
    name: "Men Formal White Shirt",
    category: "men",
    tags: ["topwear", "office"],
    price: 999,
    discount: 15,
    rating: 4.3,
    stock: 10,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQyeoL4D6PCcrPuTWThTdROlRnAzoy7A0xx6FDZR66vDbRHzECNlO86ow5937s5NHt9tySdTPLDlMZz-cbAAAR8xFzgY8Qo2U3-KoAAgLHbP4Vu3qR4KCKSMpwMA3iBm-2M-ptu6v2VVug&usqp=CAc",
  },
  {
    id: "3",
    name: "Men Printed Casual Shirt",
    category: "men",
    tags: ["topwear", "sale"],
    price: 450,
    discount: 30,
    rating: 4.6,
    stock: 18,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR0he0ZcVb-B9_E6viORHOU_ivBJOjLGu_h2o0gqtzM8Ifm4G3A3acwBLJ1drSiAsns6WBIw_nMAQP4eHuiGBNpxWXq3vAEraphjXukigKltPacWEf68snGJg",
  },
  {
    id: "4",
    name: "Men Denim Shirt",
    category: "men",
    tags: ["topwear", "trending"],
    price: 799,
    discount: 25,
    rating: 4.4,
    stock: 12,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTxZ8TENOIdT39aDGPJ9FO6emw_QeCh4t3hbMWSTG5eEJH7E8ep-cFPNxhyhPElMjgOV4H6XJnWWWO2Hz_Bj6Q55vHajRJM36tEI7UDcCgfXAu9poSu-hZP",
  },
  {
    id: "5",
    name: "Men Checkered Shirt",
    category: "men",
    tags: ["topwear"],
    price: 399,
    discount: 20,
    rating: 4.3,
    stock: 16,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSq_BsUl6FEdJtu4bjBDtWmEfRj_NjFSCZpUTWp0RC2kWs_mgIrDwRtiXbnA8MGxzTJ87TWn1asxd9eAjkWY-cEdyXn3xPyHnoQI_crV8qaC-rv5BjdzKz7",
  },
  {
    id: "6",
    name: "Men Party Wear Shirt",
    category: "men",
    tags: ["topwear", "sale"],
    price: 499,
    discount: 35,
    rating: 4.8,
    stock: 7,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSTERRd29m3ek959ujon7K3DyEDRKU7pa4CF0clgawLLJcptK6H73UzI58HWJuDShEIdWwI3N2NDiiyvKXy4v16oJESZxM8yQTkg-Kos_WTb92mZFcw2D5p",
  },
  {
    id: "7",
    name: "Men Linen Summer Shirt",
    category: "men",
    tags: ["topwear", "summer"],
    price: 899,
    discount: 18,
    rating: 4.6,
    stock: 14,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTTlhObAIO8aF4atqpAUjQwczdBVILp62vdPWUaxNjUDsEbN6w4DEPakunkqUv25YOf5CNoOcuSXWYv7d7yvrCxOly14CG--W922I_EpNxrv_5KeGIRkUcasg",
  },
  {
    id: "8",
    name: "Men Solid Black Shirt",
    category: "men",
    tags: ["topwear", "office"],
    price: 250,
    discount: 22,
    rating: 4.5,
    stock: 11,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSpupgHbTFN_17OlhhM9B-VBrUu3NV-4i4B8S0AJPYIBKEi-_TGhdt0PUa6j1VasQ6Edint-yQUgrlj5ogejzqq-U9S5daA",
  },
  {
    id: "9",
    name: "Men Casual Grey Shirt",
    category: "men",
    tags: ["topwear"],
    price: 499,
    discount: 20,
    rating: 4.4,
    stock: 19,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRwUQu0eozKD-sYloRYDEcez5HigoryrVWLHbEcBCqkdUFSDD5_v40xPWWeRezRvBZ99opBtFKofeU8ZUo498WfPpzvAtZgSA",
  },
  {
    id: "10",
    name: "Men Slim Fit Shirt",
    category: "men",
    tags: ["topwear", "trending"],
    price: 350,
    discount: 25,
    rating: 4.6,
    stock: 13,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRj4SwO8oZb1NVllIW1_FfY3QBQnk1TBo5df4TeKVBHmJs0FCF8-7M69milWu5n8O26GNgX0UG5RSD3WGKpRLOtHkQ_m_Z4a8A7o7EDME4myEe_tQ_656rMow",
  },

  {
    id: "11",
    name: "Men Cotton T-Shirt",
    category: "men",
    tags: ["topwear", "sale"],
    price: 600,
    discount: 30,
    rating: 4.3,
    stock: 22,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQqODCDNpwMTAnDY8yu410_ixSj4ielQS5MuLrmYa5Srn21NsR9bHlvd_DUQolTPEaEvIDyhf2O5UhokV2saSz4McrHk_DL7qVe5L8hoMB3C1grXSt5JhYQ",
  },
  {
    id: "12",
    name: "Men Polo T-Shirt",
    category: "men",
    tags: ["topwear"],
    price: 200,
    discount: 20,
    rating: 4.4,
    stock: 17,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRpEjUGxe3M-dT61ZXMc7w0FDFYV_fRpAahPEh-s1oTo_nNji2ECA5bAuFDxpTP4-iHN2mIVBr4xlJQa8g9GeNotS9GM_NEag",
  },
  {
    id: "13",
    name: "Men Hooded Sweatshirt",
    category: "men",
    tags: ["winter",'new',  "trending"],
    price: 699,
    discount: 35,
    rating: 4.7,
    stock: 9,
    image: "https://image.hm.com/assets/hm/b6/8f/b68f8925c6cbce864d2f95dfb54c7078dba8ad76.jpg",
  },
  {
    id: "14",
    name: "Men Denim Jacket",
    category: "men",
    tags: ["winter"],
    price: 599,
    discount: 30,
    rating: 4.6,
    stock: 8,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSGneQwuxEHBhPktgf8A4vWNbYLRc19BuWRxkEJP3wjZQPhCm-HSxN_QIYm_5R8KLoe6pXOc7a0t4WNuTcVAQ9pqej6TVCgLc3ocJ_u9yPl",
  },
  {
    id: "15",
    name: "Men Track Pants",
    category: "men",
    tags: ["bottomwear"],
    price: 699,
    discount: 25,
    rating: 4.2,
    stock: 20,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRHjJHz6LsIU3iw7f8oxvbs30MU2lLMQH7cCx0jlSF2dzJoKodjFed6ywaSfcR88QpVlyNxxABpS_SXHQdtNrfXJJB-JHYxKxfrcFFNYVB4UAWdXw1gdpd6",
  },
  {
    id: "16",
    name: "Men Casual Jeans",
    category: "men",
    tags: ["bottomwear", "trending"],
    price: 799,
    discount: 28,
    rating: 4.5,
    stock: 14,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQbwNCAROr0k9YT2_QN5Z45qz8XqEEdWYRaYQh9i_nQ1T2t099cuyj0QuMdOiX04dhNjroAjRT36kObtYPkjNXWZdo05fsfyeJAinJpuQZAD1WZX4drkx0Z",
  },
  {
    id: "17",
    name: "Men Formal Trousers",
    category: "men",
    tags: ["bottomwear", "office"],
    price: 899,
    discount: 18,
    rating: 4.3,
    stock: 12,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQSVlMqVCkkoHYS3EJEKD5A-d62h_zFDeNk4kZiiSKCXPTRLCS_fpG_jFsacy90cARpni2xp5ocNSsIdKRzSmUs-5ZF47eCnspr-N3TQNF6hUOvGM9YNSAqMQ",
  },
  {
    id: "18",
    name: "Men Nightwear Pajama Set",
    category: "men",
    tags: ["nightwear"],
    price: 499,
    discount: 22,
    rating: 4.4,
    stock: 16,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQV7Jv55aZQ7YEJCwVWTWuPDsqVtQiTIRPTDhnbpIX6TCIg6ErnIsO22vpV6AyNH3aNgnR2ipTMhB0J3qiXoCS7Es_aup3Rmm4lmCJqbRY",
  },
  {
    id: "19",
    name: "Men Ethnic Kurta",
    category: "men",
    tags: ["ethnic",'new',  "festival"],
    price: 599,
    discount: 30,
    rating: 4.6,
    stock: 10,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR5A9u-pTfl5rKfFqwqAY8I7eqUwpmcLK97q-x7f09VnAX50mTxPF5dga571c_dIdwG735LBW1AmiRdnFwxo__1Td3nuEwC0q2Bek5McUH5I4UThpwZSxVj",
  },
  {
    id: "20",
    name: "Men Sherwani Set",
    category: "men",
    tags: ["ethnic", "sale"],
    price: 999,
    discount: 40,
    rating: 4.8,
    stock: 5,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTEM26CPBvXNxC6Ud2MsRLEBdhNupxlpZ-Ut2BAsnnbKiB8S_vnukjCzcOPTx_o5lX-rzEZc0ogn_-9NxJsrLc_-TmOug58vNPDlxrQAG6zwDmE0q9LoNdGzw",
  },

  {
    id: "21",
    name: "Men Winter Jacket",
    category: "men",
    tags: ["winter"],
    price: 399,
    discount: 35,
    rating: 4.7,
    stock: 7,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSxOW5totObJJsyv0Ntu3zvACBiPRbPxoEQTNY6T_GwWP9x_zxOgEF-72A6or-41hkQcQr8PuLPKZDp5kW8twCt7Cw0QEpazrJshSDIagAZ9hNX3HaBmX7i",
  },
  {
    id: "22",
    name: "Men Casual Shorts",
    category: "men",
    tags: ["bottomwear", "summer"],
    price: 299,
    discount: 20,
    rating: 4.3,
    stock: 21,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSWPY2odUPFiPqVcD6WEHAhHTQhGj_lFVLffAgomb0BxLKsxCm5APd6XICG3x6sveIUZSsQmRUMzLIUPAjhXHk2l5OAHhn_8xdiqk-tRsal9N3VzI9knHSJ",
  },
  {
    id: "23",
    name: "Men Printed Night Shirt",
    category: "men",
    tags: ["nightwear"],
    price: 999,
    discount: 25,
    rating: 4.4,
    stock: 18,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSoa1mfe8Pcc3jOeVNpzAhGzhOFytndGbyvj2TZtjXer-42_yn0-iUY_DSw8ekHbi-Z6mSJyYTITIV_MKscKA-Va3RYU_ZTOj74RU0hhS1eHojfuCv-lJxb",
  },
  {
    id: "24",
    name: "Men Office Blazer",
    category: "men",
    tags: ["western", "office"],
    price: 499,
    discount: 30,
    rating: 4.6,
    stock: 6,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ8lV0Btn5NrmWZ7rAcPYJhb6Fga2wNU6T0QclluMd34z7PBKnVMmIIfKZemGSKKyVic4x0bQrj6fQyzkZ5ga1cN1Fwrk118ehZZeqhnhvu_gtNk7jd0cU5lA",
  },
  {
    id: "25",
    name: "Men Gym Vest",
    category: "men",
    tags: ["topwear", "sale"],
    price: 699,
    discount: 35,
    rating: 4.2,
    stock: 25,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS2ITHbuwKmg0vASG5ZmuVo6lLFDQIhb1QV2KwfQwRQQoF8EYao67Dl8vCyMTCVMbFOBGVBE2qYH9-1vC95KIJZobfHZGBF",
  },

  {
    id: "26",
    name: "Men Cargo Pants",
    category: "men",
    tags: ["bottomwear", "trending"],
    price: 899,
    discount: 28,
    rating: 4.5,
    stock: 13,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRqgQr1V2we6pWMVRxgBMvgUyl3AjpTUodt7ZlEXrn3SI3oIprma807CmHg-Z1RHP-nGX_9aRTOo2QZzaRV24Uzo2BO37eUE2szmk0OEHU",
  },
  {
    id: "27",
    name: "Men Lounge Wear Set",
    category: "men",
    tags: ["nightwear"],
    price: 499,
    discount: 30,
    rating: 4.4,
    stock: 16,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQmHmKuTs1xFLhc7GLUQ0tKbztxddusPsUqbF0VZeLdNwwiL1vXEk9fqup4jXSPKceLqEBz4nN9FBcTGVZ1J23F1EmlJY6YhuRYg10nRlxlvnwpKWGvIYJWNw",
  },
  {
    id: "28",
    name: "Men Festival Kurta Pajama",
    category: "men",
    tags: ["ethnic"],
    price: 599,
    discount: 35,
    rating: 4.7,
    stock: 8,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSTcVYn0lL6UON3hc-ZERUp-wk53KOdU2u5ROoWwhJB8APx6IQPSGudRvMO0wyUoS88BPX-s9lsKa0mEAkOUZJXTICRNzA8Fpekz9qIRrRQtmCdALUkj6LQbw",
  },
  {
    id: "29",
    name: "Men Winter Hoodie",
    category: "men",
    tags: ["winter", "sale"],
    price: 999,
    discount: 40,
    rating: 4.8,
    stock: 9,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQaujD1Bwy9yugS0Dt2HZ9BKFEHyrAjqCQe5dgGzUHl960aHHbE34nIp8p5JU8mi5RHCxxlqF4fVwT3QsZkeLBirVchwyJJ",
  },
  {
    id: "30",
    name: "Men Casual Sleeveless Tee",
    category: "men",
    tags: ["topwear", "summer"],
    price: 599,
    discount: 25,
    rating: 4.1,
    stock: 28,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTxv7s5YAVNoyzWHgtdus_8EbgM-Z45oVQxGCSKD4WTb61vH3CytMYhOG2JkIfftYTpgZ8JdrXFMAv0RE17FtGz5yf-u9Uwng",
  },
  
  {
    id: "31",
    name: "Women Floral Kurti",
    category: "women",
    tags: ["ethnic", "trending"],
    price: 899,
    discount: 30,
    rating: 4.6,
    stock: 14,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQYrjtuv2Mi9r9TOHRSg5xLX80OcVpjMDCNqwV1XGrF-5anhTp3NI9PBhUdQyDAM9XgJ3lxNPnaHCQ_n7blXlhF32uUM706OzHDzfPP304d",
  },
  {
    id: "32",
    name: "Women Anarkali Dress",
    category: "women",
    tags: ["ethnic", "festival"],
    price: 599,
    discount: 35,
    rating: 4.8,
    stock: 9,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTNayOQWxEuyyG6d5O6DVZRUvCwt6nuP8UDBxl49Xc79qYout1WBEAsAFrSzrpijuKAUyCDNhQL4sK_ONKHvw8uXyXwIbgQrbh7muuotHY0LTeBMiG4AkE_Eg",
  },
  {
    id: "33",
    name: "Women Cotton Saree",
    category: "women",
    tags: ["ethnic"],
    price: 999,
    discount: 25,
    rating: 4.5,
    stock: 11,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTMXVS1sA5fviemxCyXLwLTFMFI9zrI6mIOD4UtvxZ-IcdmEcYhakrijBamlZgKwBdn-bDOQI-5eYM64Q4XNt-qyEjZOJqPgZG9ihYdwtrs",
  },
  {
    id: "34",
    name: "Women Party Wear Gown",
    category: "women",
    tags: ["western", "sale"],
    price: 499,
    discount: 40,
    rating: 4.7,
    stock: 7,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRnxJKBS3_N9g9so7-jSTBPp2fGpTHmOmR3DdzKGLKquz2Fn4cLLa6ZC01U84QcpKTkZUNAT57q4ThbT32hPEv8Oy5bGifDVz53Losfwt3OYInCSuxVRv4IuQ",
  },
  {
    id: "35",
    name: "Women Casual Top",
    category: "women",
    tags: ["topwear"],
    price: 199,
    discount: 20,
    rating: 4.3,
    stock: 20,
    image: "https://image.hm.com/assets/hm/65/16/6516bed3dd9d753bd82e5724dfbfc6e9289284dd.jpg",
  },

  {
    id: "36",
    name: "Women Denim Jacket",
    category: "women",
    tags: ["winter", "western"],
    price: 799,
    discount: 30,
    rating: 4.6,
    stock: 10,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRQ1nnavCO89TaPH2Xch9ZYknkau41dIdDl3HUNrApDqqjc6iSN_dOx0R8E_v08lDJsyjbdL90L3i_M1s5WENA2Wn3FiZ77",
  },
  {
    id: "37",
    name: "Women Office Wear Blazer",
    category: "women",
    tags: ["office", "western"],
    price: 499,
    discount: 25,
    rating: 4.6,
    stock: 9,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR_3t7kIhHTVACkQhU_M6aWifRq7wX-P4c8WBb2L4OAM7gIx_CafmSwSA55O3K4pSNJvETThbMFq23aZ8uGa2M72LrV1twJG5C9oRMUsX023o5JL8m-eqHl294",
  },
  {
    id: "38",
    name: "Women Palazzo Pants",
    category: "women",
    tags: ["bottomwear"],
    price: 599,
    discount: 22,
    rating: 4.4,
    stock: 16,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQi8VvK0MAgY6BqqpciaLYiNOlzxVoKtHaNtZn1lw-6BXP-c1dJT5ORL2iK_eERy1N91sTgenR1I6PYllA-B5FVmwaHA0O4KduoEZwsa7Ets4st6_nPR8rUiw",
  },
  {
    id: "39",
    name: "Women Nightwear Cotton Set",
    category: "women",
    tags: ["nightwear", "sale"],
    price: 299,
    discount: 30,
    rating: 4.5,
    stock: 18,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRL0TNO2QVYdd2BtOtwpTLhsZU5UXxK52OWiuhxd6akn1hzaABeT1k3QVOjemKD0I4Cr__iBKF98i36ITFKodoZk93CA9hYOIsfPYYJjs4Vb5LhPJ3nVhNH",
  },
  {
    id: "40",
    name: "Women Western Maxi Dress",
    category: "women",
    tags: ["western", "trending"],
    price: 799,
    discount: 35,
    rating: 4.7,
    stock: 10,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSG92FXsYABA0R_Bx4KmapuV4D7S50IHxnHPU8hpkyciSkXQrbDgyLVMCaORS0fzp-vVE8Tc0VHFK4vFhJGr61FdrLKwXz-AtERHDd6_NwFYQWlwr2A5l2NvR0",
  },

  {
    id: "41",
    name: "Women Ethnic Kurta Set",
    category: "women",
    tags: ["ethnic", "festival"],
    price: 599,
    discount: 40,
    rating: 4.8,
    stock: 7,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSksmmoW_cmZf2UVr0qIFQ6CYS1qqLj3_igIx4p1snqsmU8HDoAxImVx_4uaLEe9NJBf7eynkBX0yRf8N6u5WPI2axX5Dt9pTSk9US9F2o",
  },
  {
    id: "42",
    name: "Women Casual Jeans",
    category: "women",
    tags: ["bottomwear", "trending"],
    price: 399,
    discount: 25,
    rating: 4.4,
    stock: 13,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQOSrMJ_4ZScJZuyIZc_1tqooNxmX6-WmaFoJwzvhaGsujE9y_BfePTjXA-Ilb598xZhirv4Ntm-bJCo7F3yZ-Air6_CoCUwIK-31ErksJvCs06YDRPkfEZqQ",
  },
  {
    id: "43",
    name: "Women Party Saree",
    category: "women",
    tags: ["ethnic", "sale"],
    price: 999,
    discount: 45,
    rating: 4.9,
    stock: 6,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRiYngmhm8BldINuKW-wHYvJpNaJha5AbOVcfRYAC8Ni1q2tVOTxLWqXu_t9As4thq9RswoAGLowD5eecKyzpEqddPpjER_9qK6WFC1IO0U",
  },
  {
    id: "44",
    name: "Women Formal Skirt",
    category: "women",
    tags: ["office", "bottomwear"],
    price: 799,
    discount: 20,
    rating: 4.3,
    stock: 12,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRq_v2EXTy18HmIzR33VTDDSODhyv3bwXVhCIBHhvcYMQ9ggHm09fvwQWO-CmHsStW6tIN8wCW7nqf9dUidbpXNkmoTp9SlEzjQPN2KlnbsXhl7gfJcEeIBpQ",
  },
  {
    id: "45",
    name: "Women Winter Sweater",
    category: "women",
    tags: ["winter"],
    price: 999,
    discount: 35,
    rating: 4.6,
    stock: 11,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRaz3jd5RnQgdwCLi29sT7Cp6WmsVPQ7gyNRceZvlr8DKTuvcLlQ34Kj-FVa1zVcDSL4m8rrSkxk-tfJ55qkBmZCL4GMohm066wQ4eD2n_PGsrqiQ2QI8JEzA",
  },

  {
    id: "46",
    name: "Women Lounge Wear Set",
    category: "women",
    tags: ["nightwear"],
    price: 499,
    discount: 28,
    rating: 4.4,
    stock: 17,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ5DcAzQBiB26pTzEGDGdF5iOpsEaVe5xkhANsRSR-rocqMD3kRC70mDfOLTJtTzR3d-vxPc3cjht88X1Hq3_V-dPyEM1lWoLpdoz6bAq-OaspDyS2nt9s6qQ",
  },
  {
    id: "47",
    name: "Women Crop Top",
    category: "women",
    tags: ["topwear", "trending"],
    price: 999,
    discount: 25,
    rating: 4.3,
    stock: 19,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSUoyx-R8j2nL1F3_NheWoEmfls-l-PiJsYAdLqbl1Rl71zaTcPMGvuzyLDvGebQn3iS_QvW5RVOp2_nSSiEkkAJzrkiqO09yL5zmTqpYxL",
  },
  {
    id: "48",
    name: "Women Ethnic Skirt",
    category: "women",
    tags: ["ethnic"],
    price: 899,
    discount: 30,
    rating: 4.5,
    stock: 14,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSTWtx_egQ32rXzRjsxoZyKBX0nIQL_-Z7M7AipGLsBx-WV7cLvPDPBa0XcQxitZ2LSinmyuiqEctGEERjB9ll0z04L6dlEDw",
  },
  {
    id: "49",
    name: "Women Office Kurti",
    category: "women",
    tags: ["office", "ethnic"],
    price: 699,
    discount: 22,
    rating: 4.4,
    stock: 16,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ5m2XDyJXRSoWsY9bNN0kZ93Y8Qsnjlxi00NW7k5rP9UiXeOwIVaKNsfI0CfWSs0hzw239Syk3crefG2JDOcCoTlxUIp2NuiPffPAdeWNell3pPtvaoV9-sPU",
  },
  {
    id: "50",
    name: "Women Party Jumpsuit",
    category: "women",
    tags: ["western", "sale"],
    price: 599,
    discount: 35,
    rating: 4.7,
    stock: 8,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRuGU9EdVc60CzbZcApfFmsgiYTsI5S2pummXy-qsrEAysrMoIGDwqMwbAfVd5jPiPY7Z6maBgCZ6lXKJDcSoKN4zJs7B-ciFTeILY6OiM",
  },

  {
    id: "51",
    name: "Women Cotton Night Dress",
    category: "women",
    tags: ["nightwear"],
    price: 499,
    discount: 20,
    rating: 4.3,
    stock: 22,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRZnC8nhbUzilumy2Og7bEyDfYjI9MHSz56LNr3LX1F2cGyaFhILIjI0sjzyIx2jmGfYpuNsa6hqL6h2TBb3W5qE8ywOiHZcgDynSZSMQqdKV_6UZcraFY0DjM",
  },
  {
    id: "52",
    name: "Women Festive Lehenga",
    category: "women",
    tags: ["ethnic", "festival"],
    price: 999,
    discount: 40,
    rating: 4.9,
    stock: 5,
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQUoLBDkm_vZruFb2_jvnjReB7dDcQySDXpY9sO98THhrNnGo-4HRmpbpogzUrJO06kPxId5mPXILLvetISh1nJDtDNRvhLYX6WjIxj3AV2gtnb6buIhwFw_Q",
  },
  {
    id: "53",
    name: "Women Casual Hoodie",
    category: "women",
    tags: ["winter"],
    price: 1299,
    discount: 30,
    rating: 4.6,
    stock: 10,
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSXN2OE62mwIamleL8y3C7z_5G9cXtRSn9ywrUm6S71eOz_os_5xhypU9sMtbgv4qEGIH_Pprt3bUyEF9MSbwi5Jkyh_AHqLjExuAQgbqVfTiJt0izMf5PbGg",
  },
  {
    id: "54",
    name: "Women Summer Top",
    category: "women",
    tags: ["topwear", "summer"],
    price: 899,
    discount: 25,
    rating: 4.2,
    stock: 24,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTsmItHdDI0qbEm4QZfZGVTnZRzZcYjj85pf9pj9RUNLcd3wJXyqNkQiWeds57-s--8sjFq_QzBh2NCRXmUhXDGyH0F4e-uuAO7vMyOkFda3iZG_aSxEZIk",
  },
  {
    id: "55",
    name: "Women Designer Saree",
    category: "women",
    tags: ["ethnic", "sale"],
    price:599,
    discount: 45,
    rating: 4.8,
    stock: 6,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQxMDCCR19MubsuOroPl9-6sXUofEXhD63XfVZ-hTj-WF9Mc0xX-nABWPcCHcnJAXSzcudjAu7lsBAFfAnX3s26nUSAWKwtyFAtozqo9csCoz3Z31IMfD5rjg",
  },

  {
    id: "56",
    name: "Women Office Pants",
    category: "women",
    tags: ["office", "bottomwear"],
    price: 999,
    discount: 20,
    rating: 4.4,
    stock: 13,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5gDV--n3w24K3mSn6yN_sEeOWiOiGUXzm1l8EUw6nBvzBVCWyFnZkbsQ&s",
  },
  {
    id: "57",
    name: "Women Party Shrug",
    category: "women",
    tags: ["western"],
    price: 299,
    discount: 30,
    rating: 4.5,
    stock: 11,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAj48mTLcMMbb5l_uzvjXbWYcJ2K1xMwmJNw&s",
  },
  {
    id: "58",
    name: "Women Lounge Pants",
    category: "women",
    tags: ["nightwear"],
    price: 499,
    discount: 25,
    rating: 4.3,
    stock: 20,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOu-lmo8yBn7x9fPaqc1gTlxDQfY0oetNxwA&s",
  },
  {
    id: "59",
    name: "Women Winter Coat",
    category: "women",
    tags: ["winter"],
    price: 699,
    discount: 35,
    rating: 4.7,
    stock: 7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAoYDYU7rzz0TmSO8eIj9vZQ4bc1TGmeCGIg&s",
  },
  {
    id: "60",
    name: "Women Casual Tunic",
    category: "women",
    tags: ["topwear"],
    price: 399,
    discount: 22,
    rating: 4.4,
    stock: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXAn1F7WQtQ9HkeuTukUkDx6kOKg7GOOEtnw&s",
  },

  {
    id: "61",
    name: "Kids School Uniform Set",
    category: "kids",
    tags: ["schooluniforms"],
    price: 599,
    discount: 20,
    rating: 4.4,
    stock: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtrI3zvjqOsLYJ85wdMhhenupf6fjHgA-GjQ&s",
  },
  {
    id: "62",
    name: "Kids Casual Cotton T-Shirt",
    category: "kids",
    tags: ["topwear", "casual"],
    price: 699,
    discount: 25,
    rating: 4.5,
    stock: 26,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYJstBD9MqP91I1M1yizodzjiSZF4MRjcBew&s",
  },
  {
    id: "63",
    name: "Kids Denim Jeans",
    category: "kids",
    tags: ["bottomwear"],
    price: 399,
    discount: 30,
    rating: 4.4,
    stock: 20,
    image: "https://www.mumkins.in/cdn/shop/products/jeans-for-kids-gl064956-lightblue-4.jpg?v=1757338207&width=1080",
  },
  {
    id: "64",
    name: "Kids Party Wear Suit",
    category: "kids",
    tags: ["party", "sale"],
    price: 499,
    discount: 40,
    rating: 4.8,
    stock: 8,
    image: "https://s.alicdn.com/@sc04/kf/Aa381c45bfbed42c887b29e4de3969f67j/Shalwar-Kameez-Indian-Punjabi-Pakistani-Patiala-Salwar-for-kids-girls-children-for-Wedding-and-Festive-Party-Wear-Dhoti-style.jpg",
  },
  {
    id: "65",
    name: "Kids Cartoon Printed Nightwear",
    category: "kids",
    tags: ["nightwear"],
    price: 999,
    discount: 28,
    rating: 4.6,
    stock: 22,
    image: "https://club96.in/cdn/shop/files/boys_night_suit.jpg?v=1752926709&width=533",
  },

  {
    id: "66",
    name: "Kids Winter Hoodie",
    category: "kids",
    tags: ["winter"],
    price: 499,
    discount: 35,
    rating: 4.7,
    stock: 14,
    image: "https://m.media-amazon.com/images/I/31UumrN4ePL._AC_SR290,290_.jpg",
  },
  {
    id: "67",
    name: "Kids Ethnic Kurta",
    category: "kids",
    tags: ["ethnic"],
    price: 399,
    discount: 30,
    rating: 4.5,
    stock: 16,
    image: "https://www.kidbea.com/cdn/shop/files/m1_1024x1024.jpg?v=1754552947",
  },
  {
    id: "68",
    name: "Kids Casual Shorts",
    category: "kids",
    tags: ["bottomwear", "summer"],
    price: 599,
    discount: 20,
    rating: 4.3,
    stock: 30,
    image: "https://www.westside.com/cdn/shop/files/301021720TEAL_1_85f31794-1fc8-432f-9dea-ebc984f7bca4.jpg?v=1751438606",
  },
  {
    id: "69",
    name: "Kids Party Frock",
    category: "kids",
    tags: ["party"],
    price: 799,
    discount: 35,
    rating: 4.7,
    stock: 11,
    image: "https://www.foreverkidz.in/cdn/shop/files/15.1.jpg?crop=center&height=2100&v=1746014654&width=1500",
  },
  {
    id: "70",
    name: "Kids Cotton Pajama Set",
    category: "kids",
    tags: ["nightwear"],
    price: 899,
    discount: 25,
    rating: 4.4,
    stock: 24,
    image: "https://club96.in/cdn/shop/files/girls_night_dress_22b72fdb-b921-4df9-b364-e70458a783dc.jpg?v=1752992514",
  },

  {
    id: "71",
    name: "Kids School uniforms Combo",
    category: "kids",
    tags: ["schooluniforms"],
    price: 299,
    discount: 15,
    rating: 4.2,
    stock: 19,
    image: "https://tiimg.tistatic.com/fp/1/007/894/kid-skin-friendly-comfortable-light-weight-soft-cotton-yellow-red-school-uniforms-234.jpg",
  },
  {
    id: "72",
    name: "Kids Casual Shirt",
    category: "kids",
    tags: ["topwear"],
    price: 899,
    discount: 20,
    rating: 4.4,
    stock: 21,
    image: "https://cdn.shopify.com/s/files/1/0590/7824/6535/files/2_1f1a1ff8-e74c-441a-a05d-53570520ef34.jpg?v=1756455394",
  },
  {
    id: "73",
    name: "Kids Festive Kurta Set",
    category: "kids",
    tags: ["ethnic", "festival"],
    price: 899,
    discount: 38,
    rating: 4.8,
    stock: 9,
    image: "https://5.imimg.com/data5/ECOM/Default/2024/4/409722900/OW/VU/OJ/8968532/1-26219b71-3285-4b7a-bf62-b5a652de9435-1000x1000.jpg",
  },
  {
    id: "74",
    name: "Kids Winter Jacket",
    category: "kids",
    tags: ["winter"],
    price: 999,
    discount: 35,
    rating: 4.7,
    stock: 10,
    image: "https://m.media-amazon.com/images/I/51JZ+weMf0L._AC_UY1100_.jpg",
  },
  {
    id: "75",
    name: "Kids Daily Wear Combo",
    category: "kids",
    tags: ["casual"],
    price: 499,
    discount: 25,
    rating: 4.4,
    stock: 28,
    image: "https://images.meesho.com/images/products/552310425/u8zga_512.webp?width=512",
  },

  {
    id: "76",
    name: "Kids Track Suit",
    category: "kids",
    tags: ["sports"],
    price: 699,
    discount: 30,
    rating: 4.6,
    stock: 13,
    image: "https://www.jiomart.com/images/product/original/rvlr54jqw1/mayneisha-kids-stylish-velvet-casual-track-suit-boys-girls-size-24-set-maroon-product-images-rvlr54jqw1-0-202309071312.jpg?im=Resize=(500,630)",
  },
  {
    id: "77",
    name: "Kids Rain Jacket",
    category: "kids",
    tags: ["winter"],
    price: 299,
    discount: 33,
    rating: 4.5,
    stock: 12,
    image: "https://assets.myntassets.com/w_200,q_50,,dpr_3,fl_progressive,f_webp/assets/images/22560254/2023/3/29/d3e02d06-c794-41ce-9e11-ac6982198e861680085504500RainJacket1.jpg",
  },
  {
    id: "78",
    name: "Kids Casual Hoodie",
    category: "kids",
    tags: ["winter", "trending"],
    price: 599,
    discount: 32,
    rating: 4.7,
    stock: 15,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNiJFOV-QzntLELUp8tIWRvyqTnk5WDHTaqw&s",
  },
  {
    id: "79",
    name: "Kids Party Wear Jacket",
    category: "kids",
    tags: ["party"],
    price: 399,
    discount: 40,
    rating: 4.9,
    stock: 7,
    image: "https://5.imimg.com/data5/SELLER/Default/2023/6/314537891/WS/MM/EV/190761565/untitled-500x500.png",
  },
  {
    id: "80",
    name: "Kids Summer Cotton Set",
    category: "kids",
    tags: ["summer"],
    price: 999,
    discount: 20,
    rating: 4.3,
    stock: 25,
    image: "https://peekaabookids.com/cdn/shop/files/JBL00210.png?v=1739291828&width=533",
  },

  {
    id: "81",
    name: "Kids Designer Party Dress",
    category: "kids",
    tags: ["party",'new',  "sale"],
    price: 599,
    discount: 45,
    rating: 4.9,
    stock: 5,
    image: "https://images.meesho.com/images/products/458624492/3gw8s_512.webp?width=512",
  },
  {
    id: "82",
    name: "Kids Casual Lounge Wear",
    category: "kids",
    tags: ["nightwear"],
    price: 899,
    discount: 22,
    rating: 4.4,
    stock: 27,
    image: "https://forkids6.in/cdn/shop/files/rn-image_picker_lib_temp_932dfdbd-7cb2-497a-a66e-31d94285ad7e.jpg?v=1764662068&width=1946",
  },
  {
    id: "83",
    name: "Kids School Sports Uniform",
    category: "kids",
    tags: ["schooluniforms"],
    price: 499,
    discount: 20,
    rating: 4.5,
    stock: 16,
    image: "https://cpimg.tistatic.com/7294291/b/1/primary-school-sports-uniform.jpg",
  },
  {
    id: "84",
    name: "Kids Cartoon Hoodie",
    category: "kids",
    tags: ["winter"],
    price: 399,
    discount: 30,
    rating: 4.6,
    stock: 18,
    image: "https://assets.myntassets.com/w_360,q_50,,dpr_2,fl_progressive,f_webp/assets/images/2025/SEPTEMBER/23/C9e0FnnK_17ad74c8b05044719195e0d2177c7127.jpg",
  },
  {
    id: "85",
    name: "Kids Fancy Festive Wear",
    category: "kids",
    tags: ["festival",'new',  "ethnic"],
    price: 299,
    discount: 38,
    rating: 4.8,
    stock: 8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3OvQg-ak4PaO96hBidWW9F0oNwT2FNjgrTA&s",
  },

  {
    id: "86",
    name: "Kids Casual Denim Shirt",
    category: "kids",
    tags: ["topwear"],
    price: 299,
    discount: 25,
    rating: 4.5,
    stock: 19,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8oYzXnnpOBiG-MCg_6bd4nxLVQwMhyqUmiA&s",
  },
  

  {
    id: "88",
    name: "Kids Winter Coat",
    category: "kids",
    tags: ["winter"],
    price: 999,
    discount: 35,
    rating: 4.7,
    stock: 9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaxWkVD4hYf1M_27Kx346RJZ8Hwav-zbFTRg&s",
  },
  {
    id: "89",
    name: "Kids Everyday Comfort Set",
    category: "kids",
    tags: ["casual"],
    price: 1199,
    discount: 25,
    rating: 4.4,
    stock: 22,
    image: "https://m.media-amazon.com/images/I/71xxGq8UP2L._AC_UF350,350_QL80_.jpg",
  },
  {
    id: "90",
    name: "Kids Premium Designer Wear",
    category: "kids",
    tags: ["party", 'new', "sale"],
    price: 999,
    discount: 45,
    rating: 4.9,
    stock: 4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8LJrXtRr-vdwhdv5GfLt4em3gsn5N-KUU1Q&s",
  },
  
  /* ================= WOMEN (91–110) ================= */
  {
    id: "91",
    name: "Women Cotton Nightwear Set",
    category: "women",
    tags: ["nightwear", "sale"],
    price: 399,
    discount: 30,
    rating: 4.5,
    stock: 20,
    image: "https://images-static.nykaa.com/media/catalog/product/8/b/8b6e759SAY-NSP-85_1.jpg?tr=w-500",
  },
  {
    id: "92",
    name: "Women Western Maxi Dress",
    category: "women",
    tags: ["western", "trending"],
    price: 899,
    discount: 35,
    rating: 4.7,
    stock: 12,
    image: "https://m.media-amazon.com/images/I/51P0IKjbwtL._AC_UY1100_.jpg",
  },
  {
    id: "93",
    name: "Women Ethnic Kurta Set",
    category: "women",
    tags: ["ethnic", "festival"],
    price: 3199,
    discount: 40,
    rating: 4.8,
    stock: 8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3Y1M4_GO-3ie5Z17D99VmTjx3MguVcWBvBQ&s",
  },
  {
    id: "94",
    name: "Women Office Wear Blazer",
    category: "women",
    tags: ["western", "topwear"],
    price: 499,
    discount: 25,
    rating: 4.6,
    stock: 10,
    image: "https://i.pinimg.com/474x/9c/6a/86/9c6a86ec5eda4576b0d6f093421adb72.jpg",
  },
  {
    id: "95",
    name: "Women Palazzo Pants",
    category: "women",
    tags: ["bottomwear"],
    price: 599,
    discount: 20,
    rating: 4.4,
    stock: 18,
    image: "https://letsdressup.in/cdn/shop/files/Black-Palazzo-Pants_1445x.jpg?v=1753097850",
  },
  {
    id: "96",
    name: "Women Party Wear Gown",
    category: "women",
    tags: ["party", "sale"],
    price: 999,
    discount: 45,
    rating: 4.9,
    stock: 6,
    image: "https://wholesuits.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2022/02/aglow-pink-color-party-wear-heavy-sequence-work-gown-rtc-5416-pink-400x800.jpeg.webp",
  },
  {
    id: "97",
    name: "Women Casual Crop Top",
    category: "women",
    tags: ["topwear", "casual"],
    price: 999,
    discount: 25,
    rating: 4.3,
    stock: 24,
    image: "https://tiimg.tistatic.com/fp/1/008/484/ladies-full-sleeves-cotton-crop-top-for-casual-wear-596.jpg",
  },
  {
    id: "98",
    name: "Women Designer Saree",
    category: "women",
    tags: ["ethnic", 'new', "brands"],
    price: 599,
    discount: 40,
    rating: 4.8,
    stock: 7,
    image: "https://www.vastradi.com/cdn/shop/files/Red-Colour-Georgette-Designer-Saree-VSLC1121641_fae759b1-9fa9-490c-9011-7a0cfc49e56d.jpg?v=1748856900",
  },
  
  {
    id: "100",
    name: "Women Winter Sweater",
    category: "women",
    tags: ["winter"],
    price: 999,
    discount: 35,
    rating: 4.7,
    stock: 9,
    image: "https://www.gillkart.com/cdn/shop/files/fqtda_512.webp?v=1730660584",
  },

  /* ================= MEN (111–120) ================= */
  {
    id: "111",
    name: "Men Casual Polo T-Shirt",
    category: "men",
    tags: ["topwear", "casual"],
    price: 499,
    discount: 25,
    rating: 4.4,
    stock: 22,
    image: "https://res.cloudinary.com/jerrick/image/upload/d_642250b563292b35f27461a7.png,f_jpg,fl_progressive,q_auto,w_1024/670ce4247c069f001d7e9f17.png",
  },
  {
    id: "112",
    name: "Men Slim Fit Jeans",
    category: "men",
    tags: ["bottomwear"],
    price: 899,
    discount: 30,
    rating: 4.5,
    stock: 16,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2CZ4KiQkMNR7fCvzwSN5AmuuaNNcXsjr_rg&s",
  },
  {
    id: "113",
    name: "Men Formal Office Blazer",
    category: "men",
    tags: ["brands", "office"],
    price: 499,
    discount: 35,
    rating: 4.7,
    stock: 8,
    image: "https://assets.ajio.com/medias/sys_master/root/20250220/TR9t/67b75a902960820c4998c478/-473Wx593H-701242602-brown-MODEL.jpg",
  },
  {
    id: "114",
    name: "Men Ethnic Kurta Set",
    category: "men",
    tags: ["ethnic", "festival"],
    price: 499,
    discount: 40,
    rating: 4.8,
    stock: 7,
    image: "https://assets.myntassets.com/dpr_1.5,q_30,w_400,c_limit,fl_progressive/assets/images/27475388/2024/2/9/8acb495a-5f63-4360-8602-c2bca6d3a3c51707470237255MenLimeGreenSequinsWovenDesignsKurtaWithPatialaSalwar1.jpg",
  },
  {
    id: "115",
    name: "Men Casual Track Pants",
    category: "men",
    tags: ["bottomwear"],
    price: 399,
    discount: 20,
    rating: 4.3,
    stock: 20,
    image: "https://images.meesho.com/images/products/492478596/ciwpb_512.webp?width=512",
  },
  {
    id: "116",
    name: "Men Winter Hoodie",
    category: "men",
    tags: ["winter"],
    price: 799,
    discount: 35,
    rating: 4.6,
    stock: 14,
    image: "https://images.meesho.com/images/products/613318437/zcmog_512.webp?width=512",
  },
  {
    id: "117",
    name: "Men Denim Jacket",
    category: "men",
    tags: ["western", "trending"],
    price: 999,
    discount: 30,
    rating: 4.7,
    stock: 11,
    image: "https://rukminim2.flixcart.com/image/480/640/xif0q/jacket/r/u/v/m-1-no-jakt-denim-iceblue-urbano-fashion-original-imah6j9grmzzecq6.jpeg?q=90",
  },
  {
    id: "118",
    name: "Men Party Wear Suit",
    category: "men",
    tags: ["party",'new',  "brands"],
    price: 499,
    discount: 45,
    rating: 4.9,
    stock: 5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYxQ05zNcpyjIixyPfBSoZIrYfIuoLfWTX6A&s",
  },
  {
    id: "119",
    name: "Men Casual Sweatshirt",
    category: "men",
    tags: ["winter", "casual"],
    price: 599,
    discount: 28,
    rating: 4.5,
    stock: 18,
    image: "https://triprindia.com/cdn/shop/files/st1601_converted_ca1af3f5-d494-4880-9cb7-27a8886aab16.jpg?v=1757599098",
  },
  {
    id: "120",
    name: "Men Trending Graphic T-Shirt",
    category: "men",
    tags: ["topwear", "trending"],
    price: 899,
    discount: 22,
    rating: 4.4,
    stock: 26,
    image: "https://images-cdn.ubuy.co.in/665aaed151378f161d43a7c6-oversized-graphic-tshirt-for-men-letter.jpg",
  },
/* ================= WOMEN (121–135) ================= */
  {
    id: "121",
    name: "Women New Arrival Floral Dress",
    category: "women",
    tags: ["new", "trending"],
    price: 499,
    discount: 30,
    rating: 4.6,
    stock: 14,
    image: "https://claura.in/cdn/shop/files/017A8404_1_1.jpg?v=1732947444",
  },
  {
    id: "122",
    name: "Women Ethnic Festival Lehenga",
    category: "women",
    tags: ["ethnic", 'new', "festival"],
    price: 999,
    discount: 40,
    rating: 4.9,
    stock: 6,
    image: "https://kgmbrand.in/wp-content/uploads/2024/10/WhatsApp-Image-2024-07-24-at-2.51.01-PM-430x573.jpeg",
  },
  {
    id: "123",
    name: "Women Casual Nightwear Set",
    category: "women",
    tags: ["nightwear"],
    price: 499,
    discount: 25,
    rating: 4.4,
    stock: 22,
    image: "https://www.sanskrutihomes.in/cdn/shop/products/IMGL4725.jpg?v=1768517711&width=1200",
  },
  {
    id: "124",
    name: "Women Office Pencil Skirt",
    category: "women",
    tags: ["bottomwear", "office"],
    price: 599,
    discount: 20,
    rating: 4.3,
    stock: 18,
    image: "https://i.pinimg.com/474x/d6/d5/e0/d6d5e0da13aacc48b10bbe63eff03c86.jpg",
  },
  {
    id: "125",
    name: "Women Western Denim Shorts",
    category: "women",
    tags: ["western", "bottomwear"],
    price: 399,
    discount: 30,
    rating: 4.5,
    stock: 16,
    image: "https://globusfashion.com/media/catalog/product/cache/94fb1b7c797cdb8a26ddec6c3c7ff154/w/b/wbwecomdnmsho9774-medblue-1.jpg",
  },
  {
    id: "126",
    name: "Women Trendy Crop Jacket",
    category: "women",
    tags: ["topwear", "trending"],
    price: 899,
    discount: 35,
    rating: 4.7,
    stock: 11,
    image: "https://street9.com/cdn/shop/products/JKT00001332_1_5ae08a63-d3f4-4d5c-90c1-e988fdf87f90.jpg?v=1751981998",
  },
  {
    id: "127",
    name: "Women Cotton  Kurti",
    category: "women",
    tags: ["ethnic",'new', "casual"],
    price: 999,
    discount: 20,
    rating: 4.2,
    stock: 28,
    image: "https://wholetex.sgp1.cdn.digitaloceanspaces.com/full/women-cotton-kurti-set-1768988247.jpg",
  },
  {
    id: "128",
    name: "Women Party Wear Western Gown",
    category: "women",
    tags: ["party", "sale"],
    price: 299,
    discount: 45,
    rating: 4.8,
    stock: 7,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8",
  },
  {
    id: "129",
    name: "Women Branded Handloom Saree",
    category: "women",
    tags: ["brands", 'new' ,"ethnic"],
    price: 499,
    discount: 35,
    rating: 4.9,
    stock: 5,
    image: "https://www.ekanalabel.com/cdn/shop/files/img402221.jpg?v=1742879417&width=1200",
  },
  {
    id: "130",
    name: "Women Lounge Wear Combo",
    category: "women",
    tags: ["nightwear", "sale"],
    price: 799,
    discount: 30,
    rating: 4.6,
    stock: 19,
    image: "https://images.meesho.com/images/products/607382823/krqgd_512.webp?width=512",
  },

  /* ================= MEN (131–140) ================= */
  {
    id: "131",
    name: "Men Oversized T-Shirt",
    category: "men",
    tags: ["new", "topwear"],
    price: 999,
    discount: 20,
    rating: 4.4,
    stock: 25,
    image: "https://veirdo.in/cdn/shop/files/18_5.jpg?v=1754545490",
  },
  {
    id: "132",
    name: "Men Branded Slim Jeans",
    category: "men",
    tags: ["brands", "bottomwear"],
    price: 299,
    discount: 30,
    rating: 4.6,
    stock: 14,
    image: "https://imagescdn.louisphilippe.com/img/app/product/3/39943326-19034685.jpg?auto=format&w=390",
  },
  {
    id: "133",
    name: "Men Ethnic Wedding Sherwani",
    category: "men",
    tags: ["ethnic", "festival"],
    price: 999,
    discount: 40,
    rating: 4.9,
    stock: 4,
    image: "https://i.etsystatic.com/41419909/r/il/247b04/6711086214/il_570xN.6711086214_nj60.jpg",
  },
  {
    id: "134",
    name: "Men Casual Joggers",
    category: "men",
    tags: ["bottomwear"],
    price: 299,
    discount: 25,
    rating: 4.3,
    stock: 20,
    image: "https://wrogn.com/cdn/shop/files/1_79759255-31a7-444c-b0e4-120912535fae.jpg?v=1710417766",
  },
  {
    id: "135",
    name: "Men Trending Printed Shirt",
    category: "men",
    tags: ["trending", "topwear"],
    price: 699,
    discount: 28,
    rating: 4.5,
    stock: 17,
    image: "https://rukminim2.flixcart.com/image/480/640/xif0q/shirt/1/9/q/xl-men-s-lycra-trending-shirts-fitoda-fashion-original-imagq3p497czthm4.jpeg?q=90",
  },

  /* ================= KIDS (141–150) ================= */
  {
    id: "141",
    name: "Kids School Uniform Combo",
    category: "kids",
    tags: ["school"],
    price: 599,
    discount: 20,
    rating: 4.3,
    stock: 18,
    image: "https://tiimg.tistatic.com/fp/1/007/894/kid-skin-friendly-comfortable-light-weight-soft-cotton-yellow-red-school-uniforms-234.jpg",
  },
  {
    id: "142",
    name: "Kids Nightwear Pajama Set",
    category: "kids",
    tags: ["nightwear"],
    price: 899,
    discount: 25,
    rating: 4.4,
    stock: 26,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZe1uYp_a3bUXdm8mkzcEd-5gT3y0A6xbSMw&s",
  },
  {
    id: "143",
    name: "Kids Party Wear Blazer Set",
    category: "kids",
    tags: ["party", "brands"],
    price: 499,
    discount: 35,
    rating: 4.7,
    stock: 9,
    image: "https://rukminim2.flixcart.com/image/480/640/xif0q/blazer/4/3/x/5-6-years-vasbct024bl-vastramay-original-imagwf4pgpxteuug.jpeg?q=90",
  },
  {
    id: "145",
    name: "Kids Winter Jacket Premium",
    category: "kids",
    tags: ["winter"],
    price: 899,
    discount: 30,
    rating: 4.6,
    stock: 12,
    image: "https://assets.myntassets.com/dpr_1.5,q_30,w_400,c_limit,fl_progressive/assets/images/2025/SEPTEMBER/6/DCkMvOV0_9036e810dae849c38acdc368a86b6ee0.jpg",
  },
  {
    id: "146",
    name: "Kids Ethnic Festival Dress",
    category: "kids",
    tags: ["ethnic", "festival"],
    price: 1299,
    discount: 40,
    rating: 4.8,
    stock: 7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH5XdvdygPrSl0rLHPwlje9HqJ842rIvW9xw&s",
  },
  {
    id: "147",
    name: "Kids Trendy Cartoon Hoodie",
    category: "kids",
    tags: ["trending", "winter"],
    price: 499,
    discount: 28,
    rating: 4.5,
    stock: 16,
    image: "https://images.meesho.com/images/products/585828424/bjqtd_512.webp?width=512",
  },
  {
    id: "149",
    name: "Kids Summer Play Wear Combo",
    category: "kids",
    tags: ["casual", "sale"],
    price: 999,
    discount: 30,
    rating: 4.4,
    stock: 24,
    image: "https://m.media-amazon.com/images/I/61n6XwU0xrL._AC_UY1100_.jpg",
  },
  {
    id: "150",
    name: "Kids Premium Designer Party Wear",
    category: "kids",
    tags: ["party", "brands"],
    price: 999,
    discount: 45,
    rating: 4.9,
    stock: 5,
    image: "https://www.anantexports.in/cdn/shop/files/rn-image_picker_lib_temp_7d035c63-f10c-463e-8320-807d338951f7.jpg?v=1696540127",
  },
  /* ===================== SCHOOL UNIFORMS (15 ITEMS) ===================== */

  {
    id: "201",
    name: "Boys School Uniform Shirt",
    category: "kids",
    tags: ["schooluniform"],
    price: 699,
    discount: 20,
    rating: 4.4,
    stock: 25,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8BiL6yDMO397BOAsbdxwzu_TLhXOLHf3AOQ&s",
  },
  {
    id: "202",
    name: "Girls School Uniform Shirt",
    category: "kids",
    tags: ["schooluniform"],
    price: 749,
    discount: 15,
    rating: 4.5,
    stock: 22,
    image: "https://images.jdmagicbox.com/quickquotes/images_main/polyester-cotton-girls-school-uniform-shirt-and-skirt-size-s-m-l-2222384554-c15r1u5u.jpg",
  },
  {
    id: "203",
    name: "Boys School Uniform Pants",
    category: "kids",
    tags: ["schooluniform"],
    price: 999,
    discount: 25,
    rating: 4.6,
    stock: 20,
    image: "https://5.imimg.com/data5/SELLER/Default/2020/12/XY/GU/ZS/64621709/img-20201209-wa0007-500x500.jpg",
  },
  {
    id: "204",
    name: "Girls School Uniform Skirt",
    category: "kids",
    tags: ["schooluniform"],
    price: 899,
    discount: 20,
    rating: 4.4,
    stock: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0P9Ov-y2U2eB-ru2iV1Ra0uunzrcYH2CTKA&s",
  },
  {
    id: "205",
    name: "Boys School Uniform Shorts",
    category: "kids",
    tags: ["schooluniform"],
    price: 799,
    discount: 18,
    rating: 4.3,
    stock: 24,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWbPNvLiD4oP-RR0rWm9oR5Rp-n1KDCTLPcg&s",
  },
  {
    id: "206",
    name: "Girls School Uniform Pinafore",
    category: "kids",
    tags: ["schooluniform"],
    price: 999,
    discount: 30,
    rating: 4.6,
    stock: 14,
    image: "https://www.globaluniforms.co.in/images/products/pinafore-school-uniform.jpg",
  },
  {
    id: "207",
    name: "School Uniform Blazer",
    category: "kids",
    tags: ["schooluniform"],
    price: 999,
    discount: 35,
    rating: 4.7,
    stock: 10,
    image: "https://lordsindia.com/cdn/shop/products/school-blazer-500x500_20BG.jpg?v=1707763115",
  },
  {
    id: "209",
    name: "School Uniform Tie",
    category: "kids",
    tags: ["schooluniform"],
    price: 299,
    discount: 10,
    rating: 4.2,
    stock: 40,
    image: "https://m.media-amazon.com/images/I/81mw8yrxGjL._AC_UY1100_.jpg",
  },
  {
    id: "210",
    name: "School Uniform Belt",
    category: "kids",
    tags: ["schooluniform"],
    price: 249,
    discount: 12,
    rating: 4.1,
    stock: 35,
    image: "https://m.media-amazon.com/images/I/51ZgfebBY0L._AC_UY1100_.jpg",
  },
  {
    id: "211",
    name: "School Uniform PE T-Shirt",
    category: "kids",
    tags: ["schooluniform"],
    price: 599,
    discount: 22,
    rating: 4.5,
    stock: 28,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRx8BkJYCQMKCCuWYYXs6sZ5xhJbV7qTyL2Ug&s",
  },
  {
    id: "212",
    name: "School Uniform PE Track Pants",
    category: "kids",
    tags: ["schooluniform"],
    price: 899,
    discount: 20,
    rating: 4.4,
    stock: 21,
    image: "https://5.imimg.com/data5/SELLER/Default/2025/2/491012400/MH/FR/AT/4283188/school-uniform-track-pant.jpg",
  },
  {
    id: "213",
    name: "School Uniform Full Set (Boys)",
    category: "kids",
    tags: ["schooluniform"],
    price: 499,
    discount: 40,
    rating: 4.8,
    stock: 8,
    image: "https://tiimg.tistatic.com/fp/1/004/902/boys-school-uniform-set-405.jpg",
  },
  {
    id: "214",
    name: "School Uniform Full Set (Girls)",
    category: "kids",
    tags: ["schooluniform"],
    price: 599,
    discount: 38,
    rating: 4.7,
    stock: 7,
    image: "https://m.media-amazon.com/images/I/61A74Rw6vXL._AC_UY1100_.jpg",
  },
];




export default PRODUCTS;
